src/templates/post-page.js
src/templates/post.module.sass

Add required time to a single post

---

gatsby-node.js
src/components/navbar/index.js

Resolves https://github.com/ertrzyiks/yummy/issues/37

Added a fixed order to the categories

---

src/templates/post.module.sass

Resolves https://github.com/ertrzyiks/yummy/issues/36

Fixed padding for multisection shopping list

---

src/components/footer/footer.module.sass
src/components/paginator/index.js
src/components/paginator/paginator.module.sass

Improve pagination

---

src/components/header/header.module.sass
src/components/header/index.js

Resolves: https://github.com/ertrzyiks/yummy/issues/39

Add a link to homepage to the yummy logo

---

recipes/obiady/makaron-z-cukinia/index.md
src/components/header/header.module.sass
src/components/menu_bars.js
src/components/menu_close.js
src/components/navbar/index.js
src/components/navbar/navbar.module.sass

Resolves https://github.com/ertrzyiks/yummy/issues/30

Hamburger menu for smaller screens

---

src/components/breadcrumbs/breadcrumbs.module.sass
src/components/breadcrumbs/index.js
src/components/time_to_prepare/index.js
src/components/time_to_prepare/time_to_prepare.module.sass
src/templates/post-page.js
src/templates/post.module.sass

Resolves: https://github.com/ertrzyiks/yummy/issues/27

Added breadcrumbs navigation on specific recipe pages

---

src/components/paginator/index.js
src/templates/post-list-by-category.js
src/templates/post-list-by-tag.js

Resolves: https://github.com/ertrzyiks/yummy/issues/47

Fixed pagination links on category and tag pages

---

gatsby-node.js
gatsby-node/categories.js
src/components/post-card/index.js
src/templates/post-list-by-category.js
src/templates/post-list.js
src/templates/post-page.js

Hopefully resolves: https://github.com/ertrzyiks/yummy/issues/55
Let's merge it after: https://github.com/ertrzyiks/yummy/pull/54

Added associated category data to the recipe object.

---

src/components/post-card/index.js
src/templates/post-list-by-category.js
src/templates/post-list-by-tag.js
src/templates/post-list.js

Fix image blinking

---

gatsby-node.js

Resolves: https://github.com/ertrzyiks/yummy/issues/59

Order tags alphabetically

---

src/templates/post-page.js

Fix disappearing head line

---

package-lock.json
package.json
src/components/paginator/__tests__/index.js
src/components/paginator/index.js
src/templates/post-list-by-category.js
src/templates/post-list-by-tag.js
src/templates/post-list.js

Use location from react router to render pagination URLs

---

src/components/breadcrumbs/breadcrumbs.module.sass
src/components/button/button.transparent-noborder.module.sass
src/components/button/button.transparent.module.sass
src/components/colors.scss
src/components/footer/footer.module.sass
src/components/header/header.module.sass
src/components/layout/layout.sass
src/components/navbar/navbar.module.sass
src/components/post-card/post-card.module.sass
src/components/searchbar/searchbar.module.sass
src/components/sidebar/sidebar.module.sass
src/templates/post.module.sass

Resolves: https://github.com/ertrzyiks/yummy/issues/71

Added color variables; reduced three colors

---

gatsby-browser.js
gatsby-node/categories.js
gatsby-node/tags.js
gatsby-ssr.js
src/components/footer/footer.module.sass
src/components/header/header.module.sass
src/components/header/index.js
src/components/layout/index.js
src/components/navbar/navbar.module.sass
src/components/paginator/index.js
src/components/polka-dot.sass
src/components/post-card/post-card.module.sass
src/templates/post.module.sass

Resolves: https://github.com/ertrzyiks/yummy/issues/52

Add page titles to category and tag pages

---

gatsby-node/categories.js
gatsby-node/tags.js
gatsby-ssr.js
recipes/sniadaniowe/batonikowy-chlebek/index.md
src/components/footer/footer.module.sass
src/components/header/header.module.sass
src/components/header/index.js
src/templates/page.module.sass

Resolves: https://github.com/ertrzyiks/yummy/issues/81.
Fixed footer text positioning to be left aligned.
Removed styles no longer required without full header on some pages.

Changes following comments in PR #74 and a footer bug fix

---

src/components/navbar/navbar.module.sass

| before | after |
| --- | --- |
| <img width="596" alt="Screenshot 2019-03-13 at 21 22 11" src="https://user-images.githubusercontent.com/2437969/54312016-23f3aa00-45d6-11e9-9c58-f93926400d44.png">| <img width="678" alt="Screenshot 2019-03-13 at 21 21 51" src="https://user-images.githubusercontent.com/2437969/54312045-3372f300-45d6-11e9-80a4-9374fe42cc2d.png">|

Fix navbar overlapped by dots

---

src/templates/post-list-by-category.js

Fix category page description

---

recipes/obiady/czipsy-ziemniaczane/index.md
recipes/sniadaniowe/batonikowy-chlebek/index.md
recipes/sniadaniowe/nalesniki/index.md
recipes/sniadaniowe/owsianka-malinowa/index.md
recipes/sniadaniowe/racuchy/index.md
src/components/post-card/index.js
src/components/post-card/post-card.module.sass
src/components/vegetarian_mark.js

Resolves: https://github.com/ertrzyiks/yummy/issues/86

Added vegetarian mark on post cards

---

src/components/navbar/index.js

Resolves: https://github.com/ertrzyiks/yummy/issues/44

Handle Esc to close the hamburger menu

---

src/components/footer/footer.module.sass
src/components/header/header.module.sass

Resolves: https://github.com/ertrzyiks/yummy/issues/84

Position the dots behind the logo and the footer text

---

gatsby-browser.js
gatsby-node/posts.js
gatsby-ssr.js
src/components/header/header.module.sass
src/components/header/index.js
src/components/layout/index.js
src/components/polka-dot.sass

Resolves: https://github.com/ertrzyiks/yummy/issues/97

Single recipe header adjustments for good dot visibility

---

src/templates/page.module.sass
src/templates/post.module.sass
src/utils/typography.js

Fix horizontal space on mobile

---

puppeteer/lib/snapshot.js

Addresses #148
Update screenshot only for the failed scenarios.

Update only failed comparisons

---

README.md
package.json

Update testing documentation

---

src/components/paginator/index.js
src/utils/paginationConsts.js
src/utils/paginationHelper.js
src/utils/paginationHelper.test.js

Resolves: https://github.com/ertrzyiks/yummy/issues/167

Refactor pages element

---

README.md
_templates/recipe/new/index.js
_templates/recipe/new/recipe.ejs
package.json
yarn.lock

Resolves: https://github.com/ertrzyiks/yummy/issues/189

Added a recipe template generator
